# Module 6 - JavaScript Advanced Topics <!-- omit in toc -->

- [Exception Handling](#Exception-Handling)
  - [try - catch - finally](#try---catch---finally)
  - [Throw](#Throw)
- [Promises](#Promises)
  - [Concept](#Concept)
  - [Consuming a promise](#Consuming-a-promise)
  - [Chaining then... then... done](#Chaining-then-then-done)
  - [Passing a promise](#Passing-a-promise)
  - [Creating a promise](#Creating-a-promise)
  - [Storing a promise](#Storing-a-promise)
  - [Reporting progress](#Reporting-progress)
- [Web worker](#Web-worker)
- [Web sockets](#Web-sockets)
- [Architecture Patterns](#Architecture-Patterns)
- [TypeScript](#TypeScript)
- [Example questions](#Example-questions)

---

## Exception Handling

- Managing failure in code
- Minimising failures in code

### try - catch - finally

For trying something that could potentially cause a problem.  API call, network call.

Something that would throw a runtime error rather than a syntax error.  Will it succeed in connecting for example

```js
try {
  // line(s) of suspicious code
} catch (err) {
  // .description
  // .message
  // .name
  // .number
  // .stack
} finally {
  // success or failure, code executes here
}
```

`try` the code
`catch` the `err` (use any name here) and can access the listed properties of the error
`finally` run the code.

---

### Throw

```js
function throwHelper() {
  var err = new Error(123, "Error in helper");
  throw err;
}

// elsewhere in code
try {
  throwHelper();
} catch (ex) {
  var msg = ex.number + ": " + ex:message;
  // log msg
}
```

Demo

```js
function isTypeOf(o, t) {
  if (t && t.charAt && t.charAt(0)) {
    return (Object.prototype.toString.call(o) === "[object " + t + "]");
  } else {
    throw new Error(123, "Error in helper")
    // throw new Error ("Args", "'t' required and must be a string.");
  }
}

console.log(isTypeOf({test: 'test'},'Object'))  // true
console.log(isTypeOf({test: 'test'},999)) //

```

---

## Promises

### Concept

If there's a possibility that a function may take more that 50 ms then this is an async function. And must be called as such.

Can also create asynchronous functions ourselves

---

### Consuming a promise



---

### Chaining then... then... done



---

### Passing a promise



---

### Creating a promise



---

### Storing a promise



---

### Reporting progress



---


---

## Web worker



---

## Web sockets



---

## Architecture Patterns



---

## TypeScript



---

## Example questions

[Module 6](./example-questions/6-example-questions.pdf)
